# Generated by Django 2.1.4 on 2018-12-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='isreaded',
            field=models.BooleanField(default=False),
        ),
    ]
