# Generated by Django 2.1.4 on 2018-12-10 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20181210_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersigned',
            name='user',
        ),
        migrations.AddField(
            model_name='usersigned',
            name='bywhom',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
