# Generated by Django 2.1.4 on 2018-12-10 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20181210_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersigned',
            name='bywhom',
        ),
        migrations.AddField(
            model_name='usersigned',
            name='_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersigned',
            name='_to',
            field=models.ManyToManyField(related_name='user_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
