# Generated by Django 2.1.4 on 2018-12-11 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20181210_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issigned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.RemoveField(
            model_name='readspost',
            name='new',
        ),
        migrations.RemoveField(
            model_name='readspost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersigned',
            name='_from',
        ),
        migrations.RemoveField(
            model_name='usersigned',
            name='_to',
        ),
        migrations.DeleteModel(
            name='Readspost',
        ),
        migrations.DeleteModel(
            name='UserSigned',
        ),
    ]
